const assert = require('node:assert/strict');
const fs = require('node:fs');
const backend = fs.readFileSync('2 src/backend/main.js', 'utf8');
const preload = fs.readFileSync('2 src/common/preload.js', 'utf8');
const html = fs.readFileSync('2 src/frontend/index.html', 'utf8');
assert.match(backend, /async function tmdbSuggestTv_/);
assert.match(backend, /results\.length >= 6/);
assert.match(backend, /serkal:tmdb:suggestTv/);
assert.match(preload, /suggestTv:\(query,lang\).*serkal:tmdb:suggestTv/);
assert.match(html, /id="titleSuggestions"/);
assert.match(html, /ARIA_TITLE_SUGGESTIONS/);
assert.match(html, /data-tmdb-id/);
assert.match(html, /selectedTmdbId \? \('#' \+ String\(selectedTmdbId\)\)/);
assert.match(html, /state\.lastQuery = q;/);
assert.match(html, /scheduleTitleSuggestions_/);
assert.match(html, /chooseTitleSuggestion_/);
assert.match(html, /ev\.key === 'ArrowDown'/);
assert.match(html, /removeAttribute\('data-tmdb-id'\)/);
assert.match(html, /resolvedTmdbId.*data-tmdb-id/s);
assert.match(html, /function closeTitleSuggestions_\(\) \{\s*titleSuggestionToken_\+\+/);
console.log('Intelligente Serieneingabe: Strukturtest OK');
