'use strict';

// Central language catalogue for every text created by the Electron backend.
// No user-visible backend message may be written directly at its call site.
const PAIRS = {
  GOOGLE_UNAVAILABLE:['SerKal konnte keine Verbindung zum Google Kalender herstellen. Bitte prüfen Sie die Anmeldung oder öffnen Sie die SerKal-Hilfe.','SerKal could not connect to Google Calendar. Please check the sign-in or open SerKal Help.'],
  TMDB_KEY_MISSING:['TMDB-API-Key fehlt.','TMDB API key is missing.'],
  TMDB_KEY_REQUIRED:['SerKal benötigt einen gültigen persönlichen TMDB-API-Key. Ohne diesen Key kann die Ersteinrichtung nicht abgeschlossen werden.','SerKal needs a valid personal TMDB API key. Setup cannot be completed without it.'],
  SETUP_SAVED:['Ersteinrichtung vollständig gespeichert','Initial setup saved completely'],
  SETUP_ROLLBACK_FAILED:['Ersteinrichtung und Rücksicherung fehlgeschlagen','Initial setup and recovery failed'],
  SETUP_SAVE_FAILED:['Die Ersteinrichtung konnte nicht vollständig gespeichert werden: {error}','Initial setup could not be saved completely: {error}'],
  LOG_FOLDER_UNSET:['Archivordner für das Log ist nicht eingerichtet.','The archive folder for the log is not configured.'],
  LOG_FOLDER_MISSING:['Archivordner für das Log wurde nicht gefunden: {folder}','The archive folder for the log was not found: {folder}'],
  LOG_WRITE_FAILED:['Log konnte nicht geschrieben werden: {error}','The log could not be written: {error}'],
  LOG_READ_FAILED:['Log konnte nicht gelesen werden: {error}','The log could not be read: {error}'],
  LOG_SAVED:['Log gespeichert.','Log saved.'], LOG_SAVE_FAILED:['Log konnte nicht gespeichert werden: {error}','The log could not be saved: {error}'],
  LOG_CLEARED:['Log geleert.','Log cleared.'], LOG_CLEAR_FAILED:['Log konnte nicht geleert werden: {error}','The log could not be cleared: {error}'],
  ARCHIVE_DEFAULT_CREATED:['Standard-Archivordner beim Erststart angelegt','Default archive folder created on first launch'],
  ARCHIVE_FOLDER_UNSET:['Archivordner ist nicht eingerichtet.','The archive folder is not configured.'], ARCHIVE_FOLDER_MISSING:['Archivordner nicht gefunden: {folder}','Archive folder not found: {folder}'],
  ARCHIVE_READ_FAILED:['Archiv konnte nicht gelesen werden: {error}','The archive could not be read: {error}'], TITLE_MISSING:['Titel fehlt.','Title is missing.'],
  ENTRY_INCOMPLETE:['Eintrag unvollständig (Staffel/Termine/Episoden fehlen).','Entry incomplete (season/dates/episodes are missing).'],
  ARCHIVE_SAVED:['Archiv gespeichert: {file} / {season}','Archive saved: {file} / {season}'], ARCHIVE_SAVE_FAILED:['Archiv konnte nicht gespeichert werden: {error}','The archive could not be saved: {error}'],
  ARCHIVE_FILENAME_INVALID:['Ungültiger Archivdateiname.','Invalid archive file name.'], ARCHIVE_FILE_MISSING:['Archivdatei nicht gefunden: {file}','Archive file not found: {file}'], ARCHIVE_NOT_FILE:['Archivdatei ist keine Datei: {file}','Archive item is not a file: {file}'],
  DELETE_NO_DATES:['Kalender beim Löschen übersprungen: Serie besitzt keine aktuellen oder zukünftigen Termine','Calendar deletion skipped: series has no current or future dates'], DELETE_ICS_UNSUPPORTED:['ICS-Kalendertermine können nicht automatisch gelöscht werden. Archivdatei wurde nicht gelöscht.','ICS calendar dates cannot be deleted automatically. The archive file was not deleted.'],
  DELETE_GOOGLE_EVENT_FAILED:['Google-Kalendertermin konnte beim Löschen nicht entfernt werden','Google Calendar event could not be removed during deletion'], DELETE_GOOGLE_UNAVAILABLE:['Die Serie wurde nicht gelöscht, weil SerKal den Google Kalender nicht erreichen konnte. Ihre Archivdatei ist unverändert.','The series was not deleted because SerKal could not reach Google Calendar. Your archive file is unchanged.'],
  DELETE_GOOGLE_IDS_DONE:['Vorhandene Google-Termine anhand echter IDs verarbeitet','Existing Google events processed using their actual IDs'], SERIES_DELETED:['Serie gelöscht: {file}','Series deleted: {file}'], DELETE_GOOGLE_FAILED:['Google-Fehler beim Löschen einer Serie','Google error while deleting a series'], DELETE_FAILED:['Serie konnte nicht gelöscht werden: {error}','Series could not be deleted: {error}'],
  SEASON_LABEL_INVALID:['Ungültige Staffelkennung.','Invalid season identifier.'], SEASON_NOT_FOUND:['Staffel nicht gefunden: {value}','Season not found: {value}'], NOTES_RULE_EVALUATED:['Notiz-Steuerregel ausgewertet','Note control rule evaluated'], ARCHIVE_CHANGES_FAILED:['Archivänderungen konnten nicht gespeichert werden: {error}','Archive changes could not be saved: {error}'],
  TMDB_NOT_CONFIGURED:['TMDB ist noch nicht eingerichtet. Bitte zuerst den TMDB-API-Key eintragen.','TMDB is not configured yet. Please enter the TMDB API key first.'], NETWORK_TMDB:['Keine Verbindung zu TMDB. Bitte Internetverbindung prüfen.','Unable to connect to TMDB. Please check your internet connection.'], TMDB_ID_MISSING:['TMDB-ID fehlt.','TMDB ID is missing.'], TMDB_POSTER_FAILED:['TMDB-Poster konnte nicht geladen werden.','The TMDB poster could not be loaded.'], TMDB_IMAGE_NETWORK:['Keine Verbindung zum TMDB-Bildserver.','Unable to connect to the TMDB image server.'], SERIES_TITLE_MISSING:['Serientitel fehlt.','Series title is missing.'],
  ICS_FIELDS_MISSING:['ICS: Titel, Jahr oder Staffel fehlt.','ICS: title, year or season is missing.'], ICS_NO_DATES:['ICS: Keine gültigen Termine vorhanden.','ICS: no valid dates are available.'], ICS_NO_BLOCKS:['ICS: Keine Terminblöcke vorhanden.','ICS: no date blocks are available.'], ICS_CREATE_FAILED:['ICS-Erzeugung fehlgeschlagen: {error}','ICS creation failed: {error}'],
  GOOGLE_OAUTH_MISSING:['Google-OAuth-Konfiguration ist in dieser SerKal-Installation nicht enthalten.','Google OAuth configuration is not included in this SerKal installation.'], GOOGLE_CLIENT_ID_MISSING:['Google-OAuth-Datei enthält keine Client-ID.','The Google OAuth file contains no client ID.'], GOOGLE_LOGIN_FAILED:['Google-Anmeldung fehlgeschlagen.','Google sign-in failed.'], GOOGLE_LOGIN_INVALID:['Ungültige Google-Anmeldung.','Invalid Google sign-in.'], GOOGLE_LOGIN_TIMEOUT:['Google-Anmeldung wurde nach fünf Minuten abgebrochen.','Google sign-in was cancelled after five minutes.'], GOOGLE_SCOPE_RELOGIN:['Vorhandene Google-Anmeldung besitzt noch nicht die Berechtigung zur automatischen Kalenderwahl. Neuanmeldung wird geöffnet.','The existing Google sign-in does not yet have permission for automatic calendar selection. A new sign-in will open.'],
  GOOGLE_CALENDAR_SEARCH:['Automatische Suche nach Kalender SerKal gestartet','Automatic search for the SerKal calendar started'], GOOGLE_CALENDAR_LIST_FAILED:['Google-Kalenderliste konnte nicht gelesen werden','Google calendar list could not be read'], GOOGLE_CALENDAR_LIST_HTTP:['Google-Kalenderliste antwortete mit Fehler {status}.','The Google calendar list returned error {status}.'], GOOGLE_CALENDAR_ID_MISSING:['Kalender SerKal wurde gefunden, besitzt aber keine Google-ID.','The SerKal calendar was found but has no Google ID.'], GOOGLE_CALENDAR_FOUND:['Kalender SerKal automatisch gefunden','SerKal calendar found automatically'], GOOGLE_CALENDAR_ID_SAVED:['Ermittelte Kalender-ID lokal gespeichert','Detected calendar ID saved locally'], GOOGLE_CALENDAR_CREATE_START:['Kalender SerKal nicht vorhanden; Neuanlage beginnt','SerKal calendar not found; creation starts'], GOOGLE_CALENDAR_CREATE_FAILED:['Kalender SerKal konnte nicht angelegt werden','SerKal calendar could not be created'], GOOGLE_CALENDAR_CREATE_HTTP:['Google konnte den Kalender SerKal nicht anlegen (Fehler {status}).','Google could not create the SerKal calendar (error {status}).'], GOOGLE_CREATED_NO_ID:['Google hat den Kalender SerKal ohne Kalender-ID angelegt.','Google created the SerKal calendar without a calendar ID.'], GOOGLE_CALENDAR_CREATED:['Kalender SerKal wurde angelegt und lokal gespeichert','SerKal calendar created and saved locally'],
  GOOGLE_API_PREPARED:['API-Aufruf vorbereitet','API request prepared'], GOOGLE_TOKEN_READY:['OAuth-Token für API-Aufruf verfügbar','OAuth token available for API request'], GOOGLE_API_RESPONSE:['API-Antwort erhalten','API response received'], GOOGLE_API_EXCEPTION:['API-Aufruf mit Ausnahme abgebrochen','API request aborted with an exception'], GOOGLE_EVENTS_CHECK_ALL_FAILED:['Google-Termine konnten nicht kalenderweit geprüft werden ({status}).','Google events could not be checked across the calendar ({status}).'], GOOGLE_EVENTS_CHECK_FAILED:['Google-Termine konnten nicht geprüft werden ({status}).','Google events could not be checked ({status}).'],
  CALENDAR_PROCESSING_START:['Kalenderverarbeitung gestartet','Calendar processing started'], CALENDAR_ENTRY_INCOMPLETE:['Kalendereintrag unvollständig.','Calendar entry is incomplete.'], CALENDAR_NO_DATES:['Keine gültigen Kalendertage vorhanden.','No valid calendar dates are available.'], CALENDAR_PAST_SKIPPED:['Kalender-Eintrag übersprungen: letzte Episode liegt vor dem aktuellen Jahr.','Calendar entry skipped: final episode is before the current year.'], GOOGLE_TARGET_DETECT:['Google-Ziel vor Eintrag wird automatisch ermittelt','Google target is detected automatically before inserting'], GOOGLE_BLOCKS_CREATED:['Terminblöcke für Google erzeugt','Date blocks created for Google'], GOOGLE_BLOCK_START:['Google-Terminblock beginnt','Google event block started'], GOOGLE_EVENT_NO_ID:['Vorhandener Google-Termin besitzt keine Event-ID.','Existing Google event has no event ID.'], GOOGLE_DUPLICATE_REMOVE_FAILED:['Doppeltermin konnte nicht entfernt werden ({status}).','Duplicate event could not be removed ({status}).'], GOOGLE_DUPLICATE_REMOVED:['Exakter Kalender-Doppeltermin entfernt','Exact duplicate calendar event removed'], GOOGLE_MANUAL_MOVE_PROTECTED:['Kalendertermin als händisch verschoben geschützt','Manually moved calendar event protected'], GOOGLE_HTTP_ERROR:['Google Kalender antwortete mit Fehler {status}.','Google Calendar returned error {status}.'], GOOGLE_MANUAL_CHANGE_PROTECTED:['Kalendertermin wegen manueller Änderung geschützt','Calendar event protected because of a manual change'], GOOGLE_EVENT_RECREATED:['Kalendertermin mit neuer Google-ID wiederangelegt','Calendar event recreated with a new Google ID'], GOOGLE_OLD_EVENT_LOST:['Der frühere Google-Termin ist gelöscht und konnte nicht neu angelegt werden.','The previous Google event was deleted and could not be recreated.'], GOOGLE_ENTRY_FINAL_FAILED:['Google-Kalendereintrag endgültig fehlgeschlagen','Google Calendar entry failed permanently'],
  MAINT_CACHE_READ_FAILED:['TMDB-Wartungscache konnte nicht gelesen werden','TMDB maintenance cache could not be read'], MAINT_NEW_SEASON_SAVE_FAILED:['Neue Staffel konnte nicht gespeichert werden.','The new season could not be saved.'], MAINT_DUPLICATE_CHECK:['Kalender-Dublettenprüfung','Calendar duplicate check'], MAINT_DUPLICATE_REMOVE_FAILED:['Kalender-Doppeltermin konnte nicht entfernt werden.','Duplicate calendar event could not be removed.'], MAINT_DUPLICATE_CLEANED:['Exakter Kalender-Doppeltermin bereinigt','Exact duplicate calendar event cleaned up'], MAINT_STALE_REMOVE_FAILED:['Veralteter SerKal-Termin konnte nicht entfernt werden.','Outdated SerKal event could not be removed.'], MAINT_GOOGLE_UPDATE_FAILED:['Google-Kalender konnte nicht aktualisiert werden.','Google Calendar could not be updated.'], MAINT_MANUAL_PROTECTED:['Wartungsänderung wegen händischer Kalenderänderung geschützt','Maintenance change protected because of a manual calendar change'], MAINT_CHANGE_APPLIED:['Wartungsänderung übernommen','Maintenance change applied'], MAINT_CHANGE_ROLLED_BACK:['Wartungsänderung zurückgerollt','Maintenance change rolled back'], MAINT_DUPLICATE_RESULT:['Kalender-Doppelprüfung: {error}','Calendar duplicate check: {error}'], MAINT_NEW_SEASON_PENDING:['Neue Staffel angekündigt, Detaildaten bei TMDB noch nicht verfügbar','New season announced; detailed data is not yet available from TMDB'], MAINT_RATE_LIMIT:['TMDB hat die Anfragezahl vorübergehend begrenzt. Wartung wurde sicher beendet.','TMDB temporarily limited the number of requests. Maintenance stopped safely.'], MAINT_ALREADY_RUNNING:['Die Wartung läuft bereits.','Maintenance is already running.'], MAINT_ARCHIVE_LOAD_FAILED:['Archiv konnte nicht geladen werden.','The archive could not be loaded.'], MAINT_READ_ARCHIVE:['Wartung liest Archiv und plant TMDB-Prüfung.','Maintenance is reading the archive and planning the TMDB check.'], MAINT_STARTED:['Desktop-Wartung gestartet','Desktop maintenance started'], MAINT_COMPARE:['TMDB-Prüfbestand wird mit dem Archiv verglichen.','TMDB check data is being compared with the archive.'], MAINT_DIFFERENCE:['TMDB-Abweichung festgestellt','TMDB difference detected'], MAINT_NO_TMDB_ID:['Archivstaffel ohne TMDB-ID übersprungen','Archive season without TMDB ID skipped'], MAINT_APPLY:['Freigegebene Wartungsänderungen werden sicher übernommen.','Approved maintenance changes are being applied safely.'], MAINT_APPLY_SUSPENDED:['Übernahme wegen unvollständigem TMDB-Prüflauf ausgesetzt','Application suspended because the TMDB check was incomplete'], MAINT_COMPLETED:['Desktop-Wartung abgeschlossen','Desktop maintenance completed'], MAINT_SAFE_STOP:['Wartung sicher beendet: {error}','Maintenance stopped safely: {error}'], MAINT_SAFE_STOP_LOG:['Desktop-Wartung sicher beendet','Desktop maintenance stopped safely'],
  TMDB_CONNECTION_OK:['TMDB-Verbindung funktioniert.','TMDB connection works.'], POSTER_STARTED:['Posterabruf gestartet','Poster request started'], POSTER_FINISHED:['Posterabruf abgeschlossen','Poster request completed'], POSTER_FAILED:['Posterabruf fehlgeschlagen','Poster request failed'], IPC_ARCHIVE_RECEIVED:['IPC Archiv-Eintrag empfangen','IPC archive entry received'], IPC_ARCHIVE_FINISHED:['IPC Archiv-Eintrag abgeschlossen','IPC archive entry completed'], IPC_CALENDAR_RECEIVED:['IPC Kalender-Eintrag empfangen','IPC calendar entry received'], IPC_CALENDAR_FINISHED:['IPC Kalender-Eintrag abgeschlossen','IPC calendar entry completed'], CALENDAR_DISABLED:['Kalender ist in SerKal deaktiviert.','Calendar is disabled in SerKal.'], CALENDAR_ICS_SELECTED:['ICS ist ausgewählt. Der eigentliche ICS-Export folgt in einer späteren SerKal-Version.','ICS is selected. The actual ICS export will follow in a later SerKal version.'], CALENDAR_NOT_CONFIGURED:['Kalender ist noch nicht eingerichtet.','Calendar is not configured yet.'], SETUP_NOT_FINISHED:['Die Ersteinrichtung ist noch nicht abgeschlossen. SerKal hat deshalb den vollständigen Assistenten wieder geöffnet; es wurde noch nichts gespeichert.','Initial setup is not complete yet. SerKal reopened the full setup assistant; nothing has been saved yet.'], TMDB_SETUP_CANCELLED:['Die TMDB-Einrichtung wurde abgebrochen. Du kannst sie jederzeit erneut öffnen, indem du eine neue Suche startest. Dort erfährst du über „Hilfe öffnen“, wie du deinen kostenlosen TMDB-API-Key erhältst.','TMDB setup was cancelled. You can reopen it by starting a new search. Open Help there to learn how to get your free TMDB API key.'], ARCHIVE_CALENDAR_SAVED:['Archiv und Google Kalender wurden gespeichert.','Archive and Google Calendar were saved.'], MAINT_BRIDGE_MISSING:['Desktop-Wartungsbrücke ist nicht geladen.','The desktop maintenance bridge is not loaded.'], DELETE_BRIDGE_MISSING:['Die neue Lösch-Brücke ist in dieser laufenden SerKal-Instanz noch nicht geladen. Bitte alle SerKal-/Electron-Fenster schließen und SerKal neu starten.','The new deletion bridge is not loaded in this running SerKal instance. Close all SerKal/Electron windows and restart SerKal.'], DEBUG_TOOLS_OPENED:['Electron-Entwicklerwerkzeuge automatisch geöffnet','Electron developer tools opened automatically']
  ,GOOGLE_CANCEL_PAGE:['SerKal wurde nicht mit Google verbunden. Dieses Fenster kann geschlossen werden.','SerKal was not connected to Google. You can close this window.']
  ,GOOGLE_SUCCESS_PAGE:['SerKal ist mit Google Kalender verbunden. Dieses Fenster kann jetzt geschlossen werden.','SerKal is connected to Google Calendar. You can close this window now.']
  ,GOOGLE_SIGNIN_FAILED:['SerKal-Google-Anmeldung fehlgeschlagen.','SerKal Google sign-in failed.']
  ,MAINT_READY:['Wartung ist bereit.','Maintenance is ready.']
  ,MAINT_REASON_PRELIMINARY:['Staffel besitzt bei TMDB bisher nur eine vorläufig erfasste Episode und bleibt unter Beobachtung.','TMDB currently lists only one preliminary episode for this season; it remains under observation.']
  ,MAINT_REASON_ANNOUNCED:['Staffel ist angekündigt, aber TMDB liefert noch keine vollständigen Episoden und Termine.','The season is announced, but TMDB does not yet provide complete episodes and dates.']
  ,MAINT_REASON_PREVIOUS_RUNNING:['Neue Staffel ist vollständig, aber die bisher letzte Archivstaffel wirkt noch laufend.','The new season is complete, but the previous archive season still appears to be running.']
  ,MAINT_REASON_COMPLETE:['Neue Staffel besitzt für jede Episode einen vollständigen TMDB-Termin.','The new season has a complete TMDB date for every episode.']
  ,MAINT_EPISODES_PROTECTED:['Episodenzahl wurde manuell geschützt und bleibt unangetastet.','The episode count was protected manually and remains unchanged.']
  ,MAINT_EPISODES_DIFFER:['Vollständige TMDB-Staffel weicht bei der Episodenzahl ab.','The complete TMDB season has a different episode count.']
  ,MAINT_EPISODES_INCOMPLETE:['TMDB-Staffel ist noch unvollständig; keine Änderung.','The TMDB season is still incomplete; no change.']
  ,MAINT_DATES_PROTECTED:['Kalendertermine wurden manuell geschützt und bleiben unangetastet.','Calendar dates were protected manually and remain unchanged.']
  ,MAINT_DATES_DIFFER:['Vollständige TMDB-Termine weichen vom Archiv ab.','Complete TMDB dates differ from the archive.']
  ,MAINT_DATES_INCOMPLETE:['TMDB-Termine sind noch unvollständig; keine Änderung.','TMDB dates are still incomplete; no change.']
  ,MAINT_BUILDING:['TMDB-Prüfbestand wird aufgebaut.','TMDB check data is being built.']
  ,MAINT_SUCCESS_SUMMARY:['Wartung abgeschlossen. {count} Archivdatei(en) geändert.','Maintenance completed. {count} archive file(s) changed.']
  ,MAINT_ERROR_SUMMARY:['Wartung mit {count} Fehler(n) sicher beendet.','Maintenance stopped safely with {count} error(s).']
  ,TMDB_KEY_INVALID:['Dieser TMDB-API-Key funktioniert nicht. Bitte prüfe ihn.','This TMDB API key does not work. Please check it.']
  ,TMDB_REQUEST_FAILED:['Die TMDB-Anfrage ist fehlgeschlagen. Bitte erneut versuchen.','The TMDB request failed. Please try again.']
  ,GOOGLE_OPEN_FAILED:['Google Kalender konnte nicht automatisch geöffnet werden: {error}','Google Calendar could not be opened automatically: {error}']
  ,TMDB_SEARCH_FAILED:['TMDB-Suche fehlgeschlagen.','TMDB search failed.']
  ,ARCHIVE_NOT_SAVED:['Archiv konnte nicht gespeichert werden.','The archive could not be saved.']
  ,ARCHIVE_LOAD_DETAIL:['Archiv konnte nicht geladen werden: {error}','The archive could not be loaded: {error}']
  ,DELETE_COMPLETED:['Löschen abgeschlossen','Deletion completed'], DELETE_FAILED_SHORT:['Löschen fehlgeschlagen','Deletion failed'], VIEWPORT_DETECTED:['Fenstergröße erkannt','Window size detected'], SEARCH_ARCHIVE_ACTIVE:['Suche und lokales Archiv aktiv','Search and local archive active']
  ,TMDB_SETUP_TITLE:['TMDB einrichten','Set up TMDB'], TMDB_SETUP_TEXT:['Für diese Funktion benötigt SerKal deinen persönlichen kostenlosen TMDB-API-Key.','For this function, SerKal needs your personal free TMDB API key.'], TMDB_PLACEHOLDER:['Persönlicher TMDB-API-Key (v3 auth)','Personal TMDB API key (v3 auth)'], CANCEL:['Abbrechen','Cancel'], OPEN_HELP:['Hilfe öffnen','Open help'], SAVE:['Speichern','Save'], ENTER_TMDB_KEY:['Bitte deinen persönlichen TMDB-API-Key eingeben.','Please enter your personal TMDB API key.'], NETWORK_TMDB_PERSONAL:['Keine Verbindung zu TMDB. Bitte die Internetverbindung prüfen.','Unable to connect to TMDB. Please check your internet connection.'], TMDB_SETUP_FAILED:['Die TMDB-Einrichtung ist fehlgeschlagen.','TMDB setup failed.']
  ,TMDB_SERIES_LOAD_FAILED:['TMDB-Seriendaten konnten nicht geladen werden.','TMDB series data could not be loaded.'], TMDB_SEASON_LOAD_FAILED:['TMDB-Staffeldaten konnten nicht geladen werden.','TMDB season data could not be loaded.'], TMDB_NOT_CONFIGURED_SHORT:['TMDB ist noch nicht eingerichtet.','TMDB is not configured yet.']
  ,EMPTY:['(leer)','(empty)']
};

function text(language, key, values) {
  const index = String(language || 'de').toLowerCase().startsWith('en') ? 1 : 0;
  const pair = PAIRS[key];
  let result = String(pair ? pair[index] : key || '');
  Object.entries(values || {}).forEach(([name, value]) => {
    result = result.replace(new RegExp('\\{' + name + '\\}', 'g'), String(value));
  });
  return result;
}

module.exports = { PAIRS, text };
